apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: thanos-ruler
  name: node-memory-rules
  namespace: monitoring
spec:
  groups:
  - name: node.memory.rules
    rules:
    - expr: |
        label_replace(
          sum by (node, id, type) (
            label_replace(label_replace(ipmi_sensor_state{job="ipmi-exporter", type="Memory"} > 1, "id", "$1", "name", "(.*)"), "type", "memory", "node", "(.*)")
          ),
          "condition", "MemoryUnhealthy", "node", "(.*)"
        )
      record: aegis_node_status_condition
