---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: aegis
  name: aegis
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    component: aegis
  sessionAffinity: None
  type: ClusterIP